# Conclusion
In global, permafrost and glacier-fed lakes account for a third of fresh water lake surface. Permafrost and glacier are key for fresh water access in two types of regions:

-   High latitude regions: where the low amount of solar radiations per sq.km reaching the ground allows for part of the land to remain frozen all year long. The partial melting provides fresh water to downstream lakes.
-   High altitude regions: glacier existing in mountainous areas provide water to downstream lakes when melting during the summer.

In North America, Canada and Alaska deeply rely on permafrost for fresh water. In the US, a few communities in the Rocky Mountains rely on glacier-fed lakes.


After studying the surface variations of six glacier-fed lakes in the Rocky Mountains, we cannot conclude that glacier retreat has had an impact on lake surface between 1985 and 2020. We believe that this is due to the glacier still providing the around the same amount of water while they exist and are of sufficient size as the melting rate during the summer is sustained. This doesn't mean that this fresh water source won't be impacted. The glaciers from the Rocky Mountains will disappear before 2050 and won't be able to provide for the area anymore.


The seasonal variations of lake surface of glacier-fed are very specific and temperature-related. The high temperatures during the summer cause the glacier to melt leading to an increase of lake surface. The steady melting rate during the summer provides a consistent amount of water to downstream lakes making them less precipitation dependent. In comparison, other lakes that aren't glacier-fed suffer from evaporation during the summer - their surface decreases with high temperature - and are highly dependent on precipitations - their surface increases with snowfalls and rainfalls.

In the past, glacier-fed lakes have been a reliable fresh water source during drought as they don't rely heavily on precipitations. Glaciers act as reservoirs, storing water from winter snowfalls and releasing it in summer. This mechanism also operates over several years, for example in the case of a particularly snowy year or a particularly dry year. As this source of fresh water is set to disappear, these regions will probably become more vulnerable to drought.
