---
title: "Untitled"
editor: visual
---
## 
```{r}
library(tidyquant)
library(tidyverse)
library(ggplot2)
library(sf)

RealSAT <- read_sf("C:\\Users\\khale\\OneDrive\\Desktop\\Exploratory Data Analysis and Visualization\\Final Project\\ReaLSAT-2-0\\ReaLSAT-2-0\\RealSAT.shp")
```

```{r}
print(dim(RealSAT))
print(head(RealSAT,15))
RealSAT |> ggplot(aes(CONTINENT)) +
  geom_bar(fill="cornflowerblue");

RealSAT |> ggplot(aes(RIVR_SCORE)) +
  geom_histogram(fill="cornflowerblue");

```
```{r}

TL <- read.csv("C:\\Users\\khale\\OneDrive\\Desktop\\Exploratory Data Analysis and Visualization\\Final Project\\TopLakes.csv")
TLnew<-TL |> 
+ left_join(RealSAT, by="Hylak_id")
> 
```

```{r}
ts1 = read.csv("C:\\Users\\khale\\OneDrive\\Desktop\\Exploratory Data Analysis and Visualization\\Final Project\\monthly_timeseries\\monthly_timeseries\\monthly_timeseries_-80_-50\\monthly_timeseries_-80_-50\\ID_800088.csv", stringsAsFactors=FALSE)

data <- ts1

dyear <- c()
dmonth <- c()
for (i in 1984:2015) {
  for (j in 0:11) {
    dyear <- c(dyear, i)
    dmonth <- c(dmonth, j)
  }
}
dyear <- as.integer(dyear)
dmonth <- as.integer(dmonth)

```

```{r}
prune_time_steps <- function(fill_ts, window_size) {
  T <- length(fill_ts)
  prn_ts <- rep(FALSE, T)
  for (j in 2:(T-1)) {
    cur_ts_before <- fill_ts[max(1, j-window_size):j]
    cur_ts_after <- fill_ts[(j+1):min(j+window_size+1, T)]
    if (mean(cur_ts_before) > 90 || mean(cur_ts_after) > 90) {
      prn_ts[j] <- TRUE
    }
  }
  if (fill_ts[1] > 90) {
    prn_ts[1] <- TRUE
  }
  if (fill_ts[T] > 90) {
    prn_ts[T] <- TRUE
  }
  return(prn_ts)
}
```


```{r}
library(ggplot2)

area_ts <- as.numeric(data[3,]) * 0.0009
fill_ts <- data[1,]
update_ts <- data[2,]
area_ts_gsw <- as.numeric(data[4,]) * 0.0009

bad_ts <- prune_time_steps(as.numeric(data[1,]), 3)
area_ts[bad_ts] <- NA
area_ts_gsw[bad_ts] <- NA

ggplot(as.data.frame(area_ts), aes(x = 1:length(area_ts), y = area_ts), color = "blue", size = 1) + geom_line()+
  geom_point() + geom_smooth(method="loess",span=.1, na.rm=FALSE)+
  #geom_line(aes(x = 1:length(area_ts_gsw), y = area_ts_gsw), color = "green", linetype = "solid", size = 1) +
  labs(x = "Time", y = "Area (sq. kms.)", title = "Area vs Time") +
  scale_x_continuous(breaks = seq(1, 384, 48), labels = dyear[seq(1, 384, 48)], limits = c(1, 384)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(axis.text = element_text(size = 15)) +
  theme(axis.title = element_text(size = 15)) +
  theme(plot.title = element_text(size = 15)) +
  theme(panel.grid = element_blank()) +
  theme(plot.margin = margin(1, 1, 1, 1, "cm"))




```
